import 'package:flutter/material.dart';
import 'package:appdemo/models/model.dart';
class Department {
  late String name;
  late String email;
  late String sdt;
  late String address;
  late List<Model> equip;
  Department({
    required this.name,
    required this.email,
    required this.sdt,
    required this.address,
    required this.equip,
  });
}

List<Department> departmentList = [
  /////////////////////////////1
  Department(
      name: 'Khoa Chẩn đoán hình ảnh',
      email: 'Khoacdhabvsl@gmail.com',
      sdt: '0912587498',
      address: "Bệnh viện đa khoa tỉnh Sơn La",
      equip:[
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang báo hỏng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00433',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang sử dụng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00431',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đã thanh lý',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00439',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đã thanh lý',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00432',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang sửa chữa',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00455',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Ngưng sử dụng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00450',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
      ]),
      ////////////////////////////////////2
  Department(
      name: 'Phòng vật tư y tế',
      email: 'phongvtyt2020@gmail.com',
      sdt: '12345678',
      address: "HN",
      equip:[
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang báo hỏng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00433',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang sử dụng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00431',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đã thanh lý',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00439',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đã thanh lý',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00432',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang sửa chữa',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00455',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Ngưng sử dụng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00450',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
      ]),
      //////////////////////////////////3
  Department(
      name: 'Khoa cấp cứu',
      email: 'Khoaccbvsl@gmail.com',
      sdt: '0912587498',
      address: "Khoa cấp cứu-Bệnh viện đa khoa tỉnh Sơn La",
      equip:[
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang báo hỏng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00433',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang sử dụng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00431',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đã thanh lý',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00439',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đã thanh lý',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00432',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang sửa chữa',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00455',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Ngưng sử dụng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00450',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
      ]),
      ///////////////////////////////////4
  Department(
      name: 'Khoa huyết học truyền máu',
      email: 'Khoahhtmvisinh@gmail.com',
      sdt: '0912587498',
      address: "BVDK Sơn La",
      equip:[
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang báo hỏng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00433',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang sử dụng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00431',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đã thanh lý',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00439',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đã thanh lý',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00432',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Đang sửa chữa',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00455',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
  Model(
      titile: 'Máy hút dịch Yuwell',
      description: 'Ngưng sử dụng',
      yearUse: 2018,
      yearMan: 2018,
      model: '7E-A',
      serial: '00450',
      manufacturer: 'Jiangsu yuyue',
      origin: 'Trung Quốc'),
      ]),
];
